pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sdkVersion: ''

steps:

- task: UseDotNet@2
  displayName: 'Use .NET 6.0.300 sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.300'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: restore
    projects: '$(Build.Repository.LocalPath)\MulitpleDb.Sample\MulitpleDb.Sample.csproj'

- task: DotNetCoreCLI@2
  enabled: true
  displayName: "Build project"
  inputs:
    command: 'build'
    projects: '$(Build.Repository.LocalPath)\MulitpleDb.Sample\MulitpleDb.Sample.csproj'
    configuration: $(buildConfiguration)   

- task: PowerShell@2  
  displayName: "NuGet packages vulnerabilities scan"  
  enabled: true  
  continueOnError: false  
  inputs:  
    filePath: '$(Build.SourcesDirectory)/nuget-vunerability-build-fail-report.ps1'  
    arguments: '''$(Build.SourcesDirectory)'' ''MulitpleDb.Sample.sln'''  
    pwsh: true 

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    projects: '$(Build.Repository.LocalPath)\MulitpleDb.Sample\MulitpleDb.Sample.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false