# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sdkVersion: ''

steps:

- task: CmdLine@2
  inputs:
    script: 'echo "$(Build.ArtifactStagingDirectory)"'

- task: PowerShell@2
  displayName: 'Read SDK version'
  enabled: false
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    script: |
      ls
      $xdoc = new-object System.Xml.XmlDocument$file = "$(Build.ArtifactStagingDirectory)\efcore-multiple-db\MulitpleDb.Sample\MulitpleDb.Sample.csproj"
      $xdoc.load($file)
      $version = $xdoc.SelectSingleNode("Project/PropertyGroup/Version/@value").Value
      echo $version.ToString()
      #echo "##vso[task.setvariable variable=sdkVersion]$version"

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '$(sdkVersion)'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: restore
    projects: '$(Build.ArtifactStagingDirectory)\MulitpleDb.Sample\MulitpleDb.Sample.csproj'

- task: DotNetCoreCLI@2
  enabled: true
  displayName: "Build project"
  inputs:
    command: 'build'
    projects: '$(Build.ArtifactStagingDirectory)\MulitpleDb.Sample\MulitpleDb.Sample.csproj'
    configuration: $(buildConfiguration)   

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    projects: '$(build.artifactStagingDirectory)\MulitpleDb.Sample\MulitpleDb.Sample.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false